### ISSUE TITLE
Deleted my fork, in favor of Markdown. 

### ISSUE THREAD

**Issue by acpmasquerade** [ludbek/natural-format#1]
Tried to go through your specification once again. I had forked your repo and had gone through possibilities what would be best.

Still, I found the markdown format much portable and clear, with less ambiguity.

I deleted the fork, in favor of markdown (once again).

**Comment by ludbek** [comment]
Natural format is what I use to take note on something. I did not invent it, I just discovered it just like many other people. It is kind of natural and intuitive.

Markdown is simpler version of [RST](http://en.wikipedia.org/wiki/ReStructuredText) but I dont find it intuitive and easy enough. So i derived [easedown](https://github.com/ludbek/easedown) from it. It is easy variant of Markdown. But still this is my personal thought, others could say similar thing about Markdown.
